#__init__.py
from Routers.embeddings_route import embeddings_router
from Routers.items_route import items_routers
from Routers.user_route import use_routers
from Routers.interactions_route import interactions_router
from Routers.recomendation_route import recomendation_router
from Routers.user_embeddings_route import user_embedding_router
# from Routers.sessions_route import session_routers