#__init__.py
from Routers.embeddings_route import embeddings_routers
from Routers.items_route import items_routers
from Routers.user_route import use_routers
from Routers.interactions_route import interactions_routers
from Routers.recomendation_route import recomendation_routers
from Routers.user_embeddings_route import user_embedding_routers
from Routers.items_embeddings_router import items_embeddings_routers
# from Routers.sessions_route import session_routers